version: '2'
services:
  zookeeper:
    image: zookeeper
    volumes:
      - ./zk/data:/data
      - ./zk/datalog:/datalog
    ports:
      - "2181:2181"
    restart: always

  kafka1:
    image: wurstmeister/kafka:0.10.1.0
    volumes:
      - ./kafka/kafka1:/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka2:
    image: wurstmeister/kafka:0.10.1.0
    volumes:
      - ./kafka/kafka2:/kafka
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.100
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-manager:
    image: intropro/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181

  elasticksearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elastic/node1/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticksearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - elasticksearch1
    volumes:
      - ./elastic/node2/:/usr/share/elasticsearch/data
    ports:
      - 9201:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    volumes:
      - ./elastic/kibana/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticksearch1
      - elasticksearch2
    links:
      -  elasticksearch1